---

database:
    type: sqlite
    path: "/tmp/db/metamorph.db"



logger:
    apipath: /tmp/metamorph_api.log
    controllerpath: /tmp/metamorph_controller.log

testing:
    inputfile: "/root/go/src/github.com/manojkva/MetaMorph/examples/node_input.json"

